version: "3.2"
services:
  authentication:
    build:
      context: ./services/auth/.
      dockerfile: Dockerfile
    ports:
      - published: 3000
        target: 3000
    env_file: ./services/auth/.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
