version: "3.2"
services:
  authentication:
    build:
      context: ./services/auth/.
      dockerfile: Dockerfile
    ports:
      - published: 3000
        target: 3000
    env_file: ./services/auth/.env
